name: testing windows workflow

on: 
  workflow_dispatch:

jobs:
  testing_job:
    runs-on: windows-latest
    steps:
      # - uses: actions/checkout@v4
      
      - name: runningg windows output
        run: hostname
